### ISSUE TITLE
LLVM v19.1.x: `error[E0425]: cannot find function, tuple struct or tuple variant `[...]` in crate `ffi`` (LLVM v18.1.x is fine)

### ISSUE THREAD

**Issue by m-ueberall** [signalapp/boring#28]
Is it just me, or is it currently not possible to build the `signal-v4.9.0` branch of this repository in order to produce `libsignal_jni.so` (as referenced by [`libsignal`](https://github.com/signalapp/libsignal) branches `v0.58.x`) using LLVM v19.1.x out of the box? No problems with LLVM v18.1.x previously (regardless of architecture):

```
root@vserver34(chroot:development-ubuntu2004-arm64):/build# grep -A12 "error\[" ./logs/compile_native_signal-cli_arm64_20241016_2.log
[...]
error[E0425]: cannot find function, tuple struct or tuple variant `GENERAL_NAME_new` in crate `ffi`
    --> /root/.cargo.libsignal/git/checkouts/boring-b37daebd62069023/59883d7/boring/src/x509/mod.rs:1671:33
     |
1671 |             let gn = cvt_p(ffi::GENERAL_NAME_new())?;
     |                                 ^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `GENERAL_NAME_dup`
     |
    ::: /tmp/libsignal_ubuntu2004-aarch64/target/aarch64-unknown-linux-gnu/release/build/boring-sys-eadff641fe63e755/out/bindings.rs:3:917978
     |
3    | ...tern "C" { pub fn GENERAL_NAME_dup (a : * mut GENERAL_NAME) -> * mut GENERAL_NAME ; } extern "C" { pub fn i2v_GENERAL_NAME (method : * const X509V3_EXT_...
     |               ------------------------------------------------------------------------ similarly named function `GENERAL_NAME_dup` defined here

For more information about this error, try `rustc --explain E0425`.
error: could not compile `boring` (lib) due to 32 previous errors
```

**Comment by jrose-signal** [comment]
Hm, I can't think why `GENERAL_NAME_new` would be omitted; it's expanded from a macro in x509v3.h. Can you attach that generated bindings.rs file? Maybe that'll help identify why the macro isn't expanding into something bindgen can recognize.

(We've use the older LLVM versions from Ubuntu to build on Linux, so we haven't been keeping an eye on the latest releases beyond what Apple ships for Mac/iOS.)

**Comment by m-ueberall** [comment]
The attached archive contains the respective `bindings.rs` files from build runs earlier today using LLVM v18.1.8 (working) and v19.1.2 (failing) for `libsignal_jni.so` from the `libsignal` branch `v0.59.0` on an x86_64/amd64 host:
[bindings_rs.zip](https://github.com/user-attachments/files/17466764/bindings_rs.zip)

**Comment by jrose-signal** [comment]
Reproduced on macOS as well using Homebrew LLVM 19 (`LIBCLANG_PATH=/opt/homebrew/opt/llvm/lib/ cargo check -p boring`). Very strange. I'll doubt it's our fault but I'll poke at it a bit to see how far upstream we can push it.

**Comment by jrose-signal** [comment]
Oh, good news, apparently bindgen 0.70.1 can handle it. And upstream has already pulled that in. We'll probably take all the changes from upstream soon, but meanwhile I can update just our branch (and then I suppose the tags on the libsignal side).

**Comment by m-ueberall** [comment]
> Oh, good news, apparently bindgen 0.70.1 can handle it.
Applied patch locally for testing purposes, can confirm it works with LLVM v19.1.2. Thanks for the quick fix!

**Comment by jrose-signal** [comment]
Sorry, I didn't look into it that far, I mostly just saw that upstream had already updated and wondered why they weren't running into this in any configurations.

**Comment by brjsp** [comment]
In that case, do you know when this upgrade will be shipped in signal-desktop?

**Comment by jrose-signal** [comment]
"Soon". This was pulled into libsignal in https://github.com/signalapp/libsignal/commit/a7fbbdb28b9dc0ae50b7f45d00a4bdcc48021769, which made it into v0.60.0, but Desktop hasn't picked that up quite yet. You can build libsignal yourself in the mean time if you really need it.
